parameters:
    default_folder: 'templates'

twig:
    default_path: '%kernel.project_dir%/%default_folder%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
